#:schema node_modules/wrangler/config-schema.json
name = "sublink-worke1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8b051339d19d409e9b0c016f7eaadd0f" }
]

[assets]
directory = "./public"
